name = "edge-chat"
main = "worker/index.ts"
compatibility_date = "2024-10-01"

[[durable_objects.bindings]]
name = "CHATROOM"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom"]

[ai]
binding = "AI"
